In [1]:
cube= lambda n: n*n*n
print(cube(3))

27


Think & Practice

You have prices = [199, 49, 999, 15, 320]. Use sorted() with a lambda key to sort the list from cheapest to most
expensive, and then again from most expensive to cheapest.

In [4]:
prices = [199, 49, 999, 15, 320]
my_list = sorted(prices, key=lambda p: p)
print(my_list)
my_list = sorted(prices, key=lambda p: p,reverse=True)
print(my_list)

[15, 49, 199, 320, 999]
[999, 320, 199, 49, 15]


Think & Practice (Harder)

You have a list of dictionaries: products = [{"name": "Pen", "price": 20}, {"name": "Bag", "price": 1500}, {"name":
"Book", "price": 350}]. Sort this list so the cheapest product comes first, using a lambda that looks at the "price" key.

In [5]:
products = [{"name": "Pen", "price": 20}, {"name": "Bag", "price": 1500}, {"name":"Book", "price": 350}]
cheapest_order = sorted(products, key=lambda p: p["price"])
print(cheapest_order)

[{'name': 'Pen', 'price': 20}, {'name': 'Book', 'price': 350}, {'name': 'Bag', 'price': 1500}]


You have words = ["cat", "elephant", "dog", "hippopotamus"]. Use filter() with a lambda to keep only words with
more than 3 letters. Predict the output.

In [8]:
words = ["cat", "elephant", "dog", "hippopotamus"]
wordwith3= list(filter(lambda w: len(w) > 3, words))
print(wordwith3)

['elephant', 'hippopotamus']


You have prices = [199, 49, 999, 15, 320]. Use map() with a lambda to apply a 10% discount to every price (multiply by
0.9), then round each result to a whole number using round().

In [11]:
prices = [199, 49, 999, 15, 320]
discount =list(map(lambda p: round(p-p*0.1),prices ))
print(discount)


[179, 44, 899, 14, 288]


You have names = ["ali", "Sara", "BILAL", "zara"]. In one line, first filter out any name that is not entirely lowercase
(hint: use str.islower()), then map the survivors to their capitalized form (hint: use str.capitalize()). Print the final list.

In [13]:
names = ["ali", "Sara", "BILAL", "zara"]
notcapital = filter(lambda n: n.islower(),names)
capital = list(map(lambda n: n.upper(),notcapital))
print(capital)

['ALI', 'ZARA']


Home Practice: Interview-Style Questions
• 1. Write a lambda that takes two numbers and returns the larger one, without using if.
• 2. Given a list of tuples (name, age), sort it by age using sorted() and a lambda key.
• 3. Given a list of numbers, use filter() and map() together to return the squares of only the odd numbers.
• 4. Explain in your own words: why can't a lambda contain a for loop?
• 5. Create a small module math_utils.py with two functions of your choice, and import and use both from another file.